name: Test Things

on:
  workflow_dispatch:

jobs:
  test_things:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        with:
          fetch-depth: 0
        uses: actions/checkout@v2

      - name: Set date environment variable
        run: echo "DATETIME=$(date +"%Y.%m.%d")" >> $GITHUB_ENV
      
      - name: Set tag number
        run: echo "TAG_NUM=$(git tag | wc -l)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image(s) to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMG_TAG: ${{ env.DATETIME }}
          LAMBDAS: preprocessor zops-reader
        run: echo $LAMBDAS | xargs -n 1 -d -t -I{} ./scripts/build-push.sh {} y